<?php


class Admin extends Utilisateur
{
    private static Int $instanceCount = 0;
    protected const TEST = "Yoyo";

    private Array $banUsers = [];
    protected String $code;

    public function generateCode(): string    {
        return str_replace("utilisateur","admin", parent::generateCode());
        //$this->code = uniqid('admin-') . "-" . time();
        //return $this->code;
    }

    /**
     * Admin constructor.
     * @param string $nom
     */
    public function __construct(string $nom)
    {
        parent::__construct($nom);
        self::instancePlus();
    }

    /*    public function display() : void {
            echo $this->setNom('tata')->getNom();
            // fait la meme chose avec la classe enfant
            echo "<p>". self::TEST . "</p>";
            echo "<p>". Admin::TEST . "</p>";

            // fait la meme chose avec le parent
            echo "<p>". parent::TEST . "</p>";
            echo "<p>". Utilisateur::TEST . "</p>";
        }*/

    /**
     * tentative de surcharge
     * @return string
     */
    public function getNom(): string    {
        return "Saka " .parent::getNom(); // TODO: Change the autogenerated stub
    }

    /**
     * add 1 instance count
     */
    public static function instancePlus(){
        self::$instanceCount++;
    }

    /**
     * return instance count
     * @return int
     */
    public static function getInstanceCount() : int {
        return self::$instanceCount;
    }
}